# Generated by Django 6.0.3 on 2026-04-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_balance_after_account_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance_after',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account'),
        ),
    ]
